import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import { BookmarkProvider } from '@/context/BookmarkContext'
import { ColorsProvider } from '@/context/ColorsContext'
import YouTubeLinks from '@/components/YouTubeLinks'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ColorsProvider>
                    <BookmarkProvider>{children}</BookmarkProvider>
                </ColorsProvider>
                <YouTubeLinks />
                <Toaster />
            </body>
        </html>
    )
}
